### ISSUE TITLE
Readme is indicating to import Table but the package is not exporting that

### ISSUE THREAD

**Issue by nick-stebbings** [adaburrows/table-web-component#5]
After following the instructions (`npm add ...` ) and the second set of imports 
```
import { ScopedRegistryHost } from '@lit-labs/scoped-registry-mixin';
import { FieldDefinitions, FieldDefinition, TableStore, Table } from '@adaburrows/table-web-component';
```

I cannot import `Table`.

Rendering as described in the instructions (`<adaburrows-table .tableStore=${this.tableStore}></adaburrows-table>`) did not work, there was no content, so I switched to headless mode.

**Comment by adaburrows** [comment]
Thanks, I forgot to test using the top level index. I think this made it past my last revision because they were using the headless mode.

**Comment by adaburrows** [comment]
Ok, I just pushed a new version that should be exporting things properly. Please check to make sure got things sorted for you.
